import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/ContactUs.module.css";
import Navbar from "@/components/navbar";
import CommitteeData from "@/Data/committee.json";
import ProfileCard from "@/components/ProfileCard";
import { useEffect } from "react";
import { useState } from "react";
import ContactForm from "@/components/ContactForm";
import Script from "next/script";
import Map from "@/components/Map";

const inter = Inter({ subsets: ["latin"] });

export default function ContactUs() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="./css/logosvg.css" />
      </Head>
      <Navbar />

      <div className={"DivCenter" + " " + styles.Title}>
        <h1>Contact Us</h1>
      </div>
      <div className={styles.wrapper}>
        <div className={styles.cardholder}>
          {CommitteeData.map((single) => {
            return <ProfileCard data={single} key={single.Id} />;
          })}
        </div>
      </div>


      <ContactForm />

      <Map />
    </>
  );
}
