import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/EventsPage.module.css";
import Navbar from "@/components/navbar";
import data from "@/Data/Department.json";
import EventCard from "@/components/EventCard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="./css/logosvg.css" />
      </Head>
      <Navbar />

      <div className={styles.wrapper}>
        <div>
          <h2>Department Events</h2>
        </div>
        <div className={styles.cardHolder}>
          {data.map((single) => {
            return <EventCard data={single} key={single.id} />;
          })}
        </div>
      </div>
    </>
  );
}
