import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/EventsPage.module.css";
import Navbar from "@/components/navbar";
import DepartmentData from "@/Data/Department.json";
import InstitutionalData from "@/Data/Institutional.json";
import ClubData from "@/Data/Club.json";
import EventCard from "@/components/EventCard";
import { useEffect } from "react";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Event() {
  const [Data,setData] = useState(InstitutionalData);

  const removeclass = () =>{
    const btns = document.querySelectorAll(".BtnEventCategory");
    for(var i=0 ; i< btns.length ; i++)
      btns[i].classList.remove("BtnEventCategoryActive")
  }
  
  const addclass = (elem) =>{
    elem.classList.add("BtnEventCategoryActive")
  }

  const HandleDepartment = (elem) =>{
    removeclass();
    addclass(elem.target);
    setData(DepartmentData);
  }
  
  const HandleInstitution = (elem) =>{
    removeclass();
    addclass(elem.target);
    setData(InstitutionalData);
  }
  
  const HandleClub = (elem) =>{
    removeclass();
    addclass(elem.target);
    setData(ClubData);
  }
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="./css/logosvg.css" />
      </Head>
      <Navbar />

      <div className={styles.wrapper}>
        <div className={styles.Title}>
          <h1>Events</h1>
        </div>

        <div className={styles.category}>
          <button onClick={HandleInstitution} className="BtnEventCategory BtnEventCategoryActive">Institutional Level</button>
          <button onClick={HandleDepartment} className="BtnEventCategory">Department Level</button>
          <button onClick={HandleClub} className="BtnEventCategory">Club Level</button>
        </div>

        <div id="BoxMain">
          <div className={styles.cardHolder}>
            {Data.map((single) => {
              return <EventCard data={single} key={single.id} />;
            })}
          </div>
        </div>
      </div>
    </>
  );
}
